version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
      - mongo
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/db_name
      - MONGODB_URL=mongodb://mongo:27017/parking-logs

  db:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=Parking

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
