version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgres://postgres:hola@192.168.47.171:5434/postgres
      - MONGODB_URL=mongodb://root:example@192.168.47.171:27017/parking-logs?authSource=admin

  db:
    image: bitnami/postgresql:latest
    ports:
      - '5434:5432'
    environment:
      - POSTGRESQL_PASSWORD=hola
      - POSTGRESQL_DATABASE=postgres

  mongo:
    image: mongo
    restart: always
    container_name: MongoDB
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=parking-logs

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    restart: always
